// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/recommendation-performance": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/products/create": {
    params: {};
  };
  "/webhooks/products/delete": {
    params: {};
  };
  "/webhooks/products/update": {
    params: {};
  };
  "/api/onboarding/filters": {
    params: {};
  };
  "/api/filter-analytics": {
    params: {};
  };
  "/api/recommendations": {
    params: {};
  };
  "/api/search-insights": {
    params: {};
  };
  "/api/admin/filters": {
    params: {};
  };
  "/api/admin/danger": {
    params: {};
  };
  "/api/sync-status": {
    params: {};
  };
  "/api/analytics": {
    params: {};
  };
  "/api/diversity": {
    params: {};
  };
  "/api/products": {
    params: {};
  };
  "/api/filters": {
    params: {};
  };
  "/api/similar": {
    params: {};
  };
  "/api/sorting": {
    params: {};
  };
  "/api/events": {
    params: {};
  };
  "/api/search": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/api/sync": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/onboarding/data-quality": {
    params: {};
  };
  "/app/onboarding/storefront": {
    params: {};
  };
  "/app/onboarding/complete": {
    params: {};
  };
  "/app/onboarding/filters": {
    params: {};
  };
  "/app/onboarding/sorting": {
    params: {};
  };
  "/app/onboarding/welcome": {
    params: {};
  };
  "/app/onboarding": {
    params: {};
  };
  "/app/onboarding/sync": {
    params: {};
  };
  "/app/onboarding/ai": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/dashboard": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/filters": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/recommendation-performance" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/webhooks/products/create" | "/webhooks/products/delete" | "/webhooks/products/update" | "/api/onboarding/filters" | "/api/filter-analytics" | "/api/recommendations" | "/api/search-insights" | "/api/admin/filters" | "/api/admin/danger" | "/api/sync-status" | "/api/analytics" | "/api/diversity" | "/api/products" | "/api/filters" | "/api/similar" | "/api/sorting" | "/api/events" | "/api/search" | "/auth/login" | "/api/sync" | "/auth/*" | "/app" | "/app/onboarding/data-quality" | "/app/onboarding/storefront" | "/app/onboarding/complete" | "/app/onboarding/filters" | "/app/onboarding/sorting" | "/app/onboarding/welcome" | "/app/onboarding" | "/app/onboarding/sync" | "/app/onboarding/ai" | "/app/additional" | "/app/dashboard" | "/app/settings" | "/app/filters";
  };
  "routes/api.recommendation-performance.jsx": {
    id: "routes/api.recommendation-performance";
    page: "/api/recommendation-performance";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.products.create.jsx": {
    id: "routes/webhooks.products.create";
    page: "/webhooks/products/create";
  };
  "routes/webhooks.products.delete.jsx": {
    id: "routes/webhooks.products.delete";
    page: "/webhooks/products/delete";
  };
  "routes/webhooks.products.update.jsx": {
    id: "routes/webhooks.products.update";
    page: "/webhooks/products/update";
  };
  "routes/api.onboarding.filters.jsx": {
    id: "routes/api.onboarding.filters";
    page: "/api/onboarding/filters";
  };
  "routes/api.filter-analytics.jsx": {
    id: "routes/api.filter-analytics";
    page: "/api/filter-analytics";
  };
  "routes/api.recommendations.jsx": {
    id: "routes/api.recommendations";
    page: "/api/recommendations";
  };
  "routes/api.search-insights.jsx": {
    id: "routes/api.search-insights";
    page: "/api/search-insights";
  };
  "routes/api.admin.filters.jsx": {
    id: "routes/api.admin.filters";
    page: "/api/admin/filters";
  };
  "routes/api.admin.danger.jsx": {
    id: "routes/api.admin.danger";
    page: "/api/admin/danger";
  };
  "routes/api.sync-status.jsx": {
    id: "routes/api.sync-status";
    page: "/api/sync-status";
  };
  "routes/api.analytics.jsx": {
    id: "routes/api.analytics";
    page: "/api/analytics";
  };
  "routes/api.diversity.jsx": {
    id: "routes/api.diversity";
    page: "/api/diversity";
  };
  "routes/api.products.jsx": {
    id: "routes/api.products";
    page: "/api/products";
  };
  "routes/api.filters.jsx": {
    id: "routes/api.filters";
    page: "/api/filters";
  };
  "routes/api.similar.jsx": {
    id: "routes/api.similar";
    page: "/api/similar";
  };
  "routes/api.sorting.jsx": {
    id: "routes/api.sorting";
    page: "/api/sorting";
  };
  "routes/api.events.jsx": {
    id: "routes/api.events";
    page: "/api/events";
  };
  "routes/api.search.jsx": {
    id: "routes/api.search";
    page: "/api/search";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/api.sync.jsx": {
    id: "routes/api.sync";
    page: "/api/sync";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/onboarding/data-quality" | "/app/onboarding/storefront" | "/app/onboarding/complete" | "/app/onboarding/filters" | "/app/onboarding/sorting" | "/app/onboarding/welcome" | "/app/onboarding" | "/app/onboarding/sync" | "/app/onboarding/ai" | "/app/additional" | "/app/dashboard" | "/app/settings" | "/app/filters";
  };
  "routes/app.onboarding.data-quality.jsx": {
    id: "routes/app.onboarding.data-quality";
    page: "/app/onboarding/data-quality";
  };
  "routes/app.onboarding.storefront.jsx": {
    id: "routes/app.onboarding.storefront";
    page: "/app/onboarding/storefront";
  };
  "routes/app.onboarding.complete.jsx": {
    id: "routes/app.onboarding.complete";
    page: "/app/onboarding/complete";
  };
  "routes/app.onboarding.filters.jsx": {
    id: "routes/app.onboarding.filters";
    page: "/app/onboarding/filters";
  };
  "routes/app.onboarding.sorting.jsx": {
    id: "routes/app.onboarding.sorting";
    page: "/app/onboarding/sorting";
  };
  "routes/app.onboarding.welcome.jsx": {
    id: "routes/app.onboarding.welcome";
    page: "/app/onboarding/welcome";
  };
  "routes/app.onboarding._index.jsx": {
    id: "routes/app.onboarding._index";
    page: "/app/onboarding";
  };
  "routes/app.onboarding.sync.jsx": {
    id: "routes/app.onboarding.sync";
    page: "/app/onboarding/sync";
  };
  "routes/app.onboarding.ai.jsx": {
    id: "routes/app.onboarding.ai";
    page: "/app/onboarding/ai";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.dashboard.jsx": {
    id: "routes/app.dashboard";
    page: "/app/dashboard";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.filters.jsx": {
    id: "routes/app.filters";
    page: "/app/filters";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/api.recommendation-performance": typeof import("./app/routes/api.recommendation-performance.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.products.create": typeof import("./app/routes/webhooks.products.create.jsx");
  "routes/webhooks.products.delete": typeof import("./app/routes/webhooks.products.delete.jsx");
  "routes/webhooks.products.update": typeof import("./app/routes/webhooks.products.update.jsx");
  "routes/api.onboarding.filters": typeof import("./app/routes/api.onboarding.filters.jsx");
  "routes/api.filter-analytics": typeof import("./app/routes/api.filter-analytics.jsx");
  "routes/api.recommendations": typeof import("./app/routes/api.recommendations.jsx");
  "routes/api.search-insights": typeof import("./app/routes/api.search-insights.jsx");
  "routes/api.admin.filters": typeof import("./app/routes/api.admin.filters.jsx");
  "routes/api.admin.danger": typeof import("./app/routes/api.admin.danger.jsx");
  "routes/api.sync-status": typeof import("./app/routes/api.sync-status.jsx");
  "routes/api.analytics": typeof import("./app/routes/api.analytics.jsx");
  "routes/api.diversity": typeof import("./app/routes/api.diversity.jsx");
  "routes/api.products": typeof import("./app/routes/api.products.jsx");
  "routes/api.filters": typeof import("./app/routes/api.filters.jsx");
  "routes/api.similar": typeof import("./app/routes/api.similar.jsx");
  "routes/api.sorting": typeof import("./app/routes/api.sorting.jsx");
  "routes/api.events": typeof import("./app/routes/api.events.jsx");
  "routes/api.search": typeof import("./app/routes/api.search.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/api.sync": typeof import("./app/routes/api.sync.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.onboarding.data-quality": typeof import("./app/routes/app.onboarding.data-quality.jsx");
  "routes/app.onboarding.storefront": typeof import("./app/routes/app.onboarding.storefront.jsx");
  "routes/app.onboarding.complete": typeof import("./app/routes/app.onboarding.complete.jsx");
  "routes/app.onboarding.filters": typeof import("./app/routes/app.onboarding.filters.jsx");
  "routes/app.onboarding.sorting": typeof import("./app/routes/app.onboarding.sorting.jsx");
  "routes/app.onboarding.welcome": typeof import("./app/routes/app.onboarding.welcome.jsx");
  "routes/app.onboarding._index": typeof import("./app/routes/app.onboarding._index.jsx");
  "routes/app.onboarding.sync": typeof import("./app/routes/app.onboarding.sync.jsx");
  "routes/app.onboarding.ai": typeof import("./app/routes/app.onboarding.ai.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.dashboard": typeof import("./app/routes/app.dashboard.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app.filters": typeof import("./app/routes/app.filters.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};